@startuml
left to right direction
skinparam packageStyle rectangle
actor User as op
package RCS{
(Show the Welcome message)
(Inicialize the Modbus Net)
(Show the path menu)
(Show the methodology path menu)
(Show the control strategy menu)
(Show specific messages)
(processing option)
(Build path)
(Management the robot arm)
(Exception Handling)
(Emergency Stop Handling)
 op -> (Start RCS)
(Emergency Stop Handling) .> (Exception Handling): extends
op -> (Choose the  path  option)
op -> (Choose the methodology construction path option)
op -> (Choose the control strategy option)
op -> (Emergency Stop Handling)
}
@enduml